### ISSUE TITLE
Does not work in appengine (1.9.28) -- go 1.4 vs go 1.5 compatibility 

### ISSUE THREAD

**Issue by fblecha** [najeira/hikaru#1]
If you're using the the current appengine sdk (1.9.28) which uses go 1.4.2, via goapp serve, you'll get:

"request.go:39: undefined: strings.LastIndexByte"  and the build will fail.

strings.LastIndexByte isn't avaiable until go 1.5 (https://golang.org/doc/go1.5) so this doesn't work until google upgrades the go sdk for appengine (http://googlecloudplatform.blogspot.com/2015/07/App-Engine-for-Go-is-Generally-Available.html)

**Comment by najeira** [comment]
Thank you! I will fix it.
